# Generated by Django 6.0.2 on 2026-03-16 16:10

import datetime
import django.db.models.deletion
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, verbose_name='الرقم')),
                ('service', models.CharField(max_length=100, verbose_name='المصلحة')),
                ('file_type', models.CharField(max_length=100, verbose_name='الملف/السجل')),
                ('document_type', models.CharField(max_length=100, verbose_name='الوثيقة')),
                ('symbol', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرمز')),
                ('student_dob', models.DateField(blank=True, null=True, verbose_name='تاريخ الازدياد (للتلاميذ)')),
                ('entry_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ الدخول')),
                ('temp_exit_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الخروج المؤقت')),
                ('elimination_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الحذف أو الإقصاء')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'وثيقة أرشيف',
                'verbose_name_plural': 'وثائق الأرشيف',
            },
        ),
        migrations.CreateModel(
            name='ClassAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50, unique=True, verbose_name='الاسم المستعار (من الملف)')),
                ('canonical_level', models.CharField(default='', max_length=50, verbose_name='المستوى الموافق (في القاعدة)')),
                ('canonical_class', models.CharField(max_length=50, verbose_name='القسم الموافق (في القاعدة)')),
            ],
            options={
                'verbose_name': 'تعيين اسم القسم',
                'verbose_name_plural': 'تعيينات أسماء الأقسام',
            },
        ),
        migrations.CreateModel(
            name='ClassShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, unique=True, verbose_name='الاسم الكامل للقسم')),
                ('shortcut', models.CharField(max_length=20, unique=True, verbose_name='اختصار القسم')),
            ],
            options={
                'verbose_name': 'اختصار القسم',
                'verbose_name_plural': 'اختصارات الأقسام',
            },
        ),
        migrations.CreateModel(
            name='ExpertAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='السنة الدراسية')),
                ('term', models.CharField(max_length=50, verbose_name='الفصل')),
                ('run_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المعالجة')),
                ('status', models.CharField(default='completed', max_length=50, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'تشغيلة تحليل الخبراء',
                'verbose_name_plural': 'تشغيلات تحليل الخبراء',
                'ordering': ['-run_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_year', models.CharField(db_index=True, max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ملف استيراد سنة سابقة',
                'verbose_name_plural': 'ملفات استيراد السنوات السابقة',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('academic_year', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=50)),
                ('class_code', models.CharField(blank=True, max_length=20, null=True)),
                ('historical_year', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('category', models.CharField(choices=[('rule', 'قانون داخلي'), ('curriculum', 'منهاج دراسي'), ('solution', 'حل سابق'), ('general', 'عام')], default='general', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='rag_docs/', verbose_name='ملف مرفق')),
                ('url', models.URLField(blank=True, null=True, verbose_name='رابط مرجعي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ذاكرة المؤسسة',
                'verbose_name_plural': 'ذاكرة المؤسسة',
            },
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المؤسسة')),
                ('academic_year', models.CharField(blank=True, max_length=50, null=True, verbose_name='السنة الدراسية')),
                ('director_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المدير')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logo/', verbose_name='شعار المؤسسة')),
                ('loan_limit', models.IntegerField(default=2, verbose_name='الحد الأقصى للإعارات')),
                ('loan_limits_by_level', models.JSONField(blank=True, default=dict, verbose_name='حدود الإعارة حسب المستوى')),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني لاستعادة كلمة المرور')),
                ('recovery_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز الاستعادة')),
                ('recovery_token_created_at', models.DateTimeField(blank=True, null=True, verbose_name='توقيت إنشاء رمز الاستعادة')),
                ('canteen_open_time', models.TimeField(blank=True, default='12:00', null=True, verbose_name='وقت فتح المطعم')),
                ('canteen_close_time', models.TimeField(blank=True, default='13:15', null=True, verbose_name='وقت غلق المطعم')),
                ('canteen_days', models.CharField(blank=True, default='0,2,3,6', max_length=50, null=True, verbose_name='أيام عمل المطعم')),
                ('ai_tone', models.CharField(default='professional', max_length=50, verbose_name='نبرة الذكاء الاصطناعي')),
                ('ai_focus', models.CharField(default='academic', max_length=50, verbose_name='تركيز الذكاء الاصطناعي')),
                ('analytics_exempt_subjects', models.JSONField(blank=True, default=list, verbose_name='المواد المعفاة من التحليل')),
            ],
            options={
                'verbose_name': 'إعدادات المؤسسة',
                'verbose_name_plural': 'إعدادات المؤسسة',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_number', models.CharField(max_length=16, unique=True, verbose_name='رقم التعريف')),
                ('last_name', models.CharField(max_length=100, verbose_name='اللقب')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('gender', models.CharField(max_length=10, verbose_name='الجنس')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('place_of_birth', models.CharField(max_length=100, verbose_name='مكان الميلاد')),
                ('academic_year', models.CharField(max_length=20, verbose_name='المستوى')),
                ('class_name', models.CharField(max_length=20, verbose_name='القسم')),
                ('class_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='رمز القسم')),
                ('is_repeater', models.BooleanField(default=False, verbose_name='معيد')),
                ('attendance_system', models.CharField(max_length=50, verbose_name='نظام التمدرس')),
                ('enrollment_number', models.CharField(max_length=50, verbose_name='رقم القيد')),
                ('enrollment_date', models.DateField(verbose_name='تاريخ التسجيل')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الخروج')),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الولي')),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='لقب واسم الأم')),
                ('address', models.TextField(blank=True, null=True, verbose_name='عنوان السكن')),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم هاتف الولي')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=students.models.student_photo_path, verbose_name='الصورة')),
            ],
            options={
                'verbose_name': 'تلميذ',
                'verbose_name_plural': 'التلاميذ',
            },
        ),
        migrations.CreateModel(
            name='SubjectAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True, verbose_name='الاسم المستعار (من الملف)')),
                ('canonical_name', models.CharField(max_length=100, verbose_name='المادة الموافقة (في القاعدة)')),
            ],
            options={
                'verbose_name': 'تعيين اسم المادة',
                'verbose_name_plural': 'تعيينات أسماء المواد',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('target_audience', models.CharField(max_length=100, verbose_name='الجمهور المستهدف')),
                ('link', models.URLField(blank=True, null=True, verbose_name='رابط الاستبيان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'استبيان',
                'verbose_name_plural': 'الإرشاد والتوجيه',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الدور')),
                ('permissions', models.JSONField(default=list, verbose_name='الصلاحيات')),
            ],
            options={
                'verbose_name': 'دور مخصص',
                'verbose_name_plural': 'أدوار مخصصة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='الرمز الوظيفي')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='اللقب')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='الاسم')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الازدياد')),
                ('rank', models.CharField(choices=[('teacher', 'أستاذ'), ('worker', 'عامل مهني'), ('admin', 'إداري')], default='worker', max_length=20, verbose_name='الرتبة')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='المادة')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='الدرجة')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='تاريخ السريان')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('social_media_link', models.URLField(blank=True, null=True, verbose_name='رابط التواصل الاجتماعي')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='الصورة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='الاسم الكامل (قديم)')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='الوظيفة (قديم)')),
                ('analytics_assignments', models.JSONField(blank=True, default=list, verbose_name='الإسنادات الخاصة بالتحليل')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_hr', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموارد البشرية',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='الدور')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='محاولات الدخول الفاشلة')),
                ('is_locked', models.BooleanField(default=False, verbose_name='الحساب مقفل')),
                ('current_session_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز الجلسة الحالي')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف الجهاز')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='الصلاحيات')),
                ('ai_mode', models.CharField(choices=[('restricted_rag', 'وضع مقيد (RAG) - مساعد إداري'), ('full_comprehensive', 'الوضع الشامل')], default='restricted_rag', max_length=30, verbose_name='صلاحيات الذكاء الاصطناعي')),
                ('totp_secret', models.CharField(blank=True, max_length=100, null=True, verbose_name='مفتاح المصادقة الثنائية')),
                ('totp_enabled', models.BooleanField(default=False, verbose_name='تفعيل المصادقة الثنائية')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='يجب تغيير كلمة المرور')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='CohortExpertData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year_level', models.CharField(max_length=20, verbose_name='المستوى')),
                ('correlation_matrix', models.JSONField(default=dict, verbose_name='مصفوفة الارتباط')),
                ('current_year_z_score_avg', models.FloatField(blank=True, null=True, verbose_name='متوسط Z-Score الحالي')),
                ('last_year_z_score_avg', models.FloatField(blank=True, null=True, verbose_name='متوسط Z-Score السابق')),
                ('cohort_effect_analysis', models.CharField(blank=True, max_length=200, null=True, verbose_name='تحليل أثر الفوج')),
                ('sensitivity_betas', models.JSONField(default=dict, verbose_name='معاملات الحساسية (Beta)')),
                ('ruling_subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='المادة الحاكمة')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_data', to='students.expertanalysisrun', verbose_name='التشغيلة')),
            ],
            options={
                'verbose_name': 'بيانات الفوج (الخبراء)',
                'verbose_name_plural': 'بيانات الأفواج (الخبراء)',
            },
        ),
        migrations.CreateModel(
            name='PendingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, verbose_name='النموذج')),
                ('action', models.CharField(max_length=20, verbose_name='الإجراء')),
                ('data', models.JSONField(verbose_name='البيانات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التوقيت')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='الحالة')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تحديث معلق',
                'verbose_name_plural': 'التحديثات المعلقة',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LibraryLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200, verbose_name='عنوان الكتاب')),
                ('loan_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ الإعارة')),
                ('loan_time', models.TimeField(auto_now_add=True, null=True, verbose_name='وقت الإعارة')),
                ('expected_return_date', models.DateField(verbose_name='تاريخ الإرجاع المحدد')),
                ('is_returned', models.BooleanField(default=False, verbose_name='تم الإرجاع')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإرجاع الفعلي')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='التلميذ')),
            ],
            options={
                'verbose_name': 'إعارة كتاب',
                'verbose_name_plural': 'إعارات الكتب',
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='التاريخ')),
                ('type', models.CharField(choices=[('NOTE', 'ملاحظة'), ('SUMMONS', 'استدعاء'), ('INFO', 'إعلان')], default='NOTE', max_length=20, verbose_name='النوع')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='students.student', verbose_name='التلميذ')),
            ],
            options={
                'verbose_name': 'مراسلة',
                'verbose_name_plural': 'المراسلات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='التاريخ')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='وقت الوصول')),
                ('type', models.CharField(choices=[('ABSENT', 'غياب'), ('LATE', 'تأخر')], max_length=20, verbose_name='النوع')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student', verbose_name='التلميذ')),
            ],
            options={
                'verbose_name': 'سجل الغياب والتأخر',
                'verbose_name_plural': 'سجلات الغياب والتأخر',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='StudentExpertData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, verbose_name='القسم')),
                ('academic_year_level', models.CharField(max_length=20, verbose_name='المستوى')),
                ('residual', models.FloatField(blank=True, null=True, verbose_name='الباقي (Residual)')),
                ('status_pattern', models.CharField(blank=True, max_length=50, null=True, verbose_name='نمط التلميذ')),
                ('current_avg', models.FloatField(blank=True, null=True, verbose_name='المعدل الحالي')),
                ('predicted_avg', models.FloatField(blank=True, null=True, verbose_name='المعدل المتوقع')),
                ('traffic_light', models.CharField(blank=True, max_length=10, null=True, verbose_name='إشارة المرور')),
                ('trend_history', models.JSONField(default=list, verbose_name='سجل الاتجاه')),
                ('net_value_added', models.FloatField(blank=True, null=True, verbose_name='القيمة المضافة الصافية')),
                ('z_score', models.FloatField(blank=True, null=True, verbose_name='الدرجة المعيارية (Z-Score)')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_data', to='students.expertanalysisrun', verbose_name='التشغيلة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='التلميذ')),
            ],
            options={
                'verbose_name': 'بيانات التلميذ (الخبراء)',
                'verbose_name_plural': 'بيانات التلاميذ (الخبراء)',
            },
        ),
        migrations.CreateModel(
            name='SubjectExemptionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, verbose_name='المادة')),
                ('scope_type', models.CharField(choices=[('student', 'تلميذ'), ('class', 'فوج'), ('level', 'مستوى')], max_length=20, verbose_name='نطاق الإعفاء')),
                ('academic_year', models.CharField(blank=True, max_length=50, null=True, verbose_name='المستوى')),
                ('class_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='رمز الفوج')),
                ('term', models.CharField(blank=True, max_length=20, null=True, verbose_name='الفصل (اختياري)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='التلميذ')),
            ],
            options={
                'verbose_name': 'قاعدة إعفاء مادة',
                'verbose_name_plural': 'قواعد إعفاء المواد',
            },
        ),
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'رسالة النظام',
                'verbose_name_plural': 'رسائل النظام',
            },
        ),
        migrations.CreateModel(
            name='TeacherAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=150, unique=True, verbose_name='الاسم المستعار (من الملف)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='students.employee', verbose_name='الأستاذ الموافق (في القاعدة)')),
            ],
            options={
                'verbose_name': 'تعيين اسم الأستاذ',
                'verbose_name_plural': 'تعيينات أسماء الأساتذة',
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='المادة')),
                ('classes', models.JSONField(default=list, verbose_name='الأقسام المسندة')),
                ('original_file', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='ملف الإسناد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='students.employee', verbose_name='الأستاذ')),
            ],
            options={
                'verbose_name': 'إسناد تربوي',
                'verbose_name_plural': 'الإسنادات التربوية',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='الإجراء')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التوقيت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل النشاط',
                'verbose_name_plural': 'سجلات النشاط',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المهمة')),
                ('description', models.TextField(verbose_name='الوصف التقني')),
                ('manager_instructions', models.TextField(blank=True, null=True, verbose_name='سياق المدير (AI Context)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('is_completed', models.BooleanField(default=False)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المسند')),
                ('assigned_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.userrole', verbose_name='الدور المسند')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
            },
        ),
        migrations.CreateModel(
            name='HistoricalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('historical_year', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.historicalstudent')),
            ],
            options={
                'unique_together': {('student', 'subject', 'term', 'historical_year')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='المادة')),
                ('term', models.CharField(max_length=50, verbose_name='الفصل')),
                ('score', models.FloatField(verbose_name='العلامة')),
                ('academic_year', models.CharField(default='2023-2024', max_length=20, verbose_name='السنة الدراسية')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='التلميذ')),
            ],
            options={
                'verbose_name': 'علامة التلميذ',
                'verbose_name_plural': 'علامات التلاميذ',
                'unique_together': {('student', 'subject', 'term', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='CanteenAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='التاريخ')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='الوقت')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='التلميذ')),
            ],
            options={
                'verbose_name': 'حضور المطعم',
                'verbose_name_plural': 'سجل حضور المطعم',
                'unique_together': {('student', 'date')},
            },
        ),
    ]
