# Generated by Django 6.0.2 on 2026-02-04 16:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id_number",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="رقم التعريف"
                    ),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="اللقب")),
                ("first_name", models.CharField(max_length=100, verbose_name="الاسم")),
                ("gender", models.CharField(max_length=10, verbose_name="الجنس")),
                ("date_of_birth", models.DateField(verbose_name="تاريخ الميلاد")),
                (
                    "place_of_birth",
                    models.CharField(max_length=100, verbose_name="مكان الميلاد"),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=20, verbose_name="المستوى"),
                ),
                ("class_name", models.CharField(max_length=20, verbose_name="القسم")),
                (
                    "attendance_system",
                    models.CharField(max_length=50, verbose_name="نظام التمدرس"),
                ),
                (
                    "enrollment_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم القيد"
                    ),
                ),
                ("enrollment_date", models.DateField(verbose_name="تاريخ التسجيل")),
                (
                    "exit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الخروج"
                    ),
                ),
                (
                    "guardian_name",
                    models.CharField(max_length=200, verbose_name="اسم الولي"),
                ),
                (
                    "mother_name",
                    models.CharField(max_length=200, verbose_name="لقب واسم الأم"),
                ),
                ("address", models.TextField(verbose_name="عنوان السكن")),
                (
                    "guardian_phone",
                    models.CharField(max_length=20, verbose_name="رقم هاتف الولي"),
                ),
                (
                    "photo_path",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="مسار الصورة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تلميذ",
                "verbose_name_plural": "التلاميذ",
            },
        ),
        migrations.CreateModel(
            name="CanteenAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="التاريخ"
                    ),
                ),
                ("time", models.TimeField(auto_now_add=True, verbose_name="الوقت")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                        verbose_name="التلميذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "حضور المطعم",
                "verbose_name_plural": "سجل حضور المطعم",
                "unique_together": {("student", "date")},
            },
        ),
    ]
