# Generated by Django 6.0.2 on 2026-02-11 19:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(max_length=50, verbose_name="الرقم"),
                ),
                ("service", models.CharField(max_length=100, verbose_name="المصلحة")),
                (
                    "file_type",
                    models.CharField(max_length=100, verbose_name="الملف/السجل"),
                ),
                (
                    "document_type",
                    models.CharField(max_length=100, verbose_name="الوثيقة"),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="الرمز"
                    ),
                ),
                (
                    "student_dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الازدياد (للتلاميذ)"
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="تاريخ الدخول"
                    ),
                ),
                (
                    "temp_exit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الخروج المؤقت"
                    ),
                ),
                (
                    "elimination_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الحذف أو الإقصاء"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
            ],
            options={
                "verbose_name": "وثيقة أرشيف",
                "verbose_name_plural": "وثائق الأرشيف",
            },
        ),
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المؤسسة")),
                (
                    "academic_year",
                    models.CharField(max_length=50, verbose_name="السنة الدراسية"),
                ),
                (
                    "director_name",
                    models.CharField(max_length=200, verbose_name="اسم المدير"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="school_logo/",
                        verbose_name="شعار المؤسسة",
                    ),
                ),
                (
                    "loan_limit",
                    models.IntegerField(default=2, verbose_name="الحد الأقصى للإعارات"),
                ),
                (
                    "admin_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="البريد الإلكتروني لاستعادة كلمة المرور",
                    ),
                ),
                (
                    "canteen_open_time",
                    models.TimeField(default="12:00", verbose_name="وقت فتح المطعم"),
                ),
                (
                    "canteen_close_time",
                    models.TimeField(default="13:15", verbose_name="وقت غلق المطعم"),
                ),
                (
                    "canteen_days",
                    models.CharField(
                        default="0,2,3,6", max_length=50, verbose_name="أيام عمل المطعم"
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات المؤسسة",
                "verbose_name_plural": "إعدادات المؤسسة",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id_number",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="رقم التعريف"
                    ),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="اللقب")),
                ("first_name", models.CharField(max_length=100, verbose_name="الاسم")),
                ("gender", models.CharField(max_length=10, verbose_name="الجنس")),
                ("date_of_birth", models.DateField(verbose_name="تاريخ الميلاد")),
                (
                    "place_of_birth",
                    models.CharField(max_length=100, verbose_name="مكان الميلاد"),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=20, verbose_name="المستوى"),
                ),
                ("class_name", models.CharField(max_length=20, verbose_name="القسم")),
                (
                    "attendance_system",
                    models.CharField(max_length=50, verbose_name="نظام التمدرس"),
                ),
                (
                    "enrollment_number",
                    models.CharField(max_length=50, verbose_name="رقم القيد"),
                ),
                ("enrollment_date", models.DateField(verbose_name="تاريخ التسجيل")),
                (
                    "exit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الخروج"
                    ),
                ),
                (
                    "guardian_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="اسم الولي"
                    ),
                ),
                (
                    "mother_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="لقب واسم الأم",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="عنوان السكن"),
                ),
                (
                    "guardian_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="رقم هاتف الولي",
                    ),
                ),
                (
                    "photo_path",
                    models.TextField(blank=True, null=True, verbose_name="مسار الصورة"),
                ),
            ],
            options={
                "verbose_name": "تلميذ",
                "verbose_name_plural": "التلاميذ",
            },
        ),
        migrations.CreateModel(
            name="SystemMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                ("active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة النظام",
                "verbose_name_plural": "رسائل النظام",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم الدور"
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(default=list, verbose_name="الصلاحيات"),
                ),
            ],
            options={
                "verbose_name": "دور مخصص",
                "verbose_name_plural": "أدوار مخصصة",
            },
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100, verbose_name="الدور")),
                (
                    "failed_login_attempts",
                    models.IntegerField(
                        default=0, verbose_name="محاولات الدخول الفاشلة"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, verbose_name="الحساب مقفل"),
                ),
                (
                    "current_session_token",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رمز الجلسة الحالي",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="معرف الجهاز",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="الصلاحيات"
                    ),
                ),
                (
                    "totp_secret",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="مفتاح المصادقة الثنائية",
                    ),
                ),
                (
                    "totp_enabled",
                    models.BooleanField(
                        default=False, verbose_name="تفعيل المصادقة الثنائية"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PendingUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=50, verbose_name="النموذج")),
                ("action", models.CharField(max_length=20, verbose_name="الإجراء")),
                ("data", models.JSONField(verbose_name="البيانات")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="التوقيت"),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=20, verbose_name="الحالة"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تحديث معلق",
                "verbose_name_plural": "التحديثات المعلقة",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LibraryLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_title",
                    models.CharField(max_length=200, verbose_name="عنوان الكتاب"),
                ),
                (
                    "loan_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="تاريخ الإعارة"
                    ),
                ),
                (
                    "loan_time",
                    models.TimeField(
                        auto_now_add=True, null=True, verbose_name="وقت الإعارة"
                    ),
                ),
                (
                    "expected_return_date",
                    models.DateField(verbose_name="تاريخ الإرجاع المحدد"),
                ),
                (
                    "is_returned",
                    models.BooleanField(default=False, verbose_name="تم الإرجاع"),
                ),
                (
                    "actual_return_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الإرجاع الفعلي"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                        verbose_name="التلميذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعارة كتاب",
                "verbose_name_plural": "إعارات الكتب",
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50, verbose_name="الإجراء")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="التوقيت"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل النشاط",
                "verbose_name_plural": "سجلات النشاط",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CanteenAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="التاريخ"
                    ),
                ),
                ("time", models.TimeField(auto_now_add=True, verbose_name="الوقت")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                        verbose_name="التلميذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "حضور المطعم",
                "verbose_name_plural": "سجل حضور المطعم",
                "unique_together": {("student", "date")},
            },
        ),
    ]
