# Generated by Django 6.0.2 on 2026-03-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectexemptionrule',
            name='scope_type',
            field=models.CharField(choices=[('school', 'المؤسسة'), ('student', 'تلميذ'), ('class', 'فوج'), ('level', 'مستوى')], max_length=20, verbose_name='نطاق الإعفاء'),
        ),
    ]
