# Generated by Django 6.0.2 on 2026-02-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="enrollment_number",
            field=models.CharField(max_length=50, verbose_name="رقم القيد"),
        ),
    ]
