# Generated by Django 6.0.2 on 2026-02-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_employee_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="loan_limits_by_level",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="حدود الإعارة حسب المستوى"
            ),
        ),
    ]
