# Generated by Django 6.0.2 on 2026-02-04 22:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_student_enrollment_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_title",
                    models.CharField(max_length=200, verbose_name="عنوان الكتاب"),
                ),
                (
                    "loan_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="تاريخ الإعارة"
                    ),
                ),
                (
                    "expected_return_date",
                    models.DateField(verbose_name="تاريخ الإرجاع المحدد"),
                ),
                (
                    "is_returned",
                    models.BooleanField(default=False, verbose_name="تم الإرجاع"),
                ),
                (
                    "actual_return_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الإرجاع الفعلي"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                        verbose_name="التلميذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعارة كتاب",
                "verbose_name_plural": "إعارات الكتب",
            },
        ),
    ]
