# Generated by Django 6.0.2 on 2026-02-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_libraryloan"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المؤسسة")),
                (
                    "academic_year",
                    models.CharField(max_length=50, verbose_name="السنة الدراسية"),
                ),
                (
                    "director_name",
                    models.CharField(max_length=200, verbose_name="اسم المدير"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="school_logo/",
                        verbose_name="شعار المؤسسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات المؤسسة",
                "verbose_name_plural": "إعدادات المؤسسة",
            },
        ),
    ]
