# Generated by Django 6.0.2 on 2026-02-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_systemmessage_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="recovery_token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="رمز الاستعادة"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="recovery_token_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="توقيت إنشاء رمز الاستعادة"
            ),
        ),
    ]
