# Generated by Django 6.0.2 on 2026-03-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_add_subject_coefficients_and_last_year_raw_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='subject_coefficients_by_level',
            field=models.JSONField(blank=True, default=dict, help_text='لحساب المعدل الفصلي المرجح والمادة الحاكمة. مثال: {"أولى متوسط": {"الرياضيات": 2, "اللغة العربية": 2}}', verbose_name='معاملات المواد حسب المستوى'),
        ),
    ]
