# Generated by Django 6.0.2 on 2026-02-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_schoolsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="photo_path",
            field=models.TextField(blank=True, null=True, verbose_name="مسار الصورة"),
        ),
    ]
