# Generated by Django 6.0.2 on 2026-02-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_schoolsettings_recovery_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="must_change_password",
            field=models.BooleanField(
                default=False, verbose_name="يجب تغيير كلمة المرور"
            ),
        ),
    ]
