# Generated by Django 6.0.2 on 2026-02-06 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_alter_student_photo_path"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("director", "مدير"),
                            ("librarian", "مكتبي"),
                            ("storekeeper", "مخزني"),
                            ("archivist", "أرشيفي"),
                            ("secretariat", "أمانة"),
                        ],
                        default="director",
                        max_length=20,
                    ),
                ),
                ("failed_attempts", models.IntegerField(default=0)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "active_session_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "device_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
