# Generated by Django 6.0.2 on 2026-02-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_employeeprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="loan_limit",
            field=models.IntegerField(default=2, verbose_name="الحد الأقصى للإعارات"),
        ),
    ]
