# Generated by Django 6.0.2 on 2026-02-20 13:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_employeeprofile_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="التاريخ"
                    ),
                ),
                (
                    "time",
                    models.TimeField(blank=True, null=True, verbose_name="وقت الوصول"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("ABSENT", "غياب"), ("LATE", "تأخر")],
                        max_length=20,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="السبب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="students.student",
                        verbose_name="التلميذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل الغياب والتأخر",
                "verbose_name_plural": "سجلات الغياب والتأخر",
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("content", models.TextField(verbose_name="المحتوى")),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="التاريخ"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NOTE", "ملاحظة"),
                            ("SUMMONS", "استدعاء"),
                            ("INFO", "إعلان"),
                        ],
                        default="NOTE",
                        max_length=20,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="تمت القراءة"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="students.student",
                        verbose_name="التلميذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "مراسلة",
                "verbose_name_plural": "المراسلات",
                "ordering": ["-date"],
            },
        ),
    ]
