# Generated by Django 6.0.2 on 2026-02-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_attendancerecord_communication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userrole",
            options={
                "ordering": ["name"],
                "verbose_name": "دور مخصص",
                "verbose_name_plural": "أدوار مخصصة",
            },
        ),
    ]
