# Generated by Django 6.0.2 on 2026-04-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_canteen_registration_meals_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="remaining_meals",
            field=models.IntegerField(default=0, verbose_name="الرصيد المتبقي للوجبات"),
        ),
    ]
