# Generated by Django 6.0.2 on 2026-02-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_alter_userrole_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="assigned_interface",
            field=models.CharField(
                choices=[
                    ("all", "كامل الصلاحيات"),
                    ("canteen", "المطعم المدرسي"),
                    ("library", "المكتبة"),
                    ("students", "تسيير التلاميذ"),
                ],
                default="all",
                max_length=50,
                verbose_name="الواجهة المخصصة",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="is_active_cloud",
            field=models.BooleanField(
                default=True, verbose_name="تفعيل الدخول السحابي"
            ),
        ),
    ]
