# Generated by Django 6.0.2 on 2026-02-07 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_useractivitylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(max_length=50, verbose_name="الرقم"),
                ),
                ("service", models.CharField(max_length=100, verbose_name="المصلحة")),
                (
                    "file_type",
                    models.CharField(max_length=100, verbose_name="الملف/السجل"),
                ),
                (
                    "document_type",
                    models.CharField(max_length=100, verbose_name="الوثيقة"),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="الرمز"
                    ),
                ),
                (
                    "student_dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الازدياد (للتلاميذ)"
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="تاريخ الدخول"
                    ),
                ),
                (
                    "temp_exit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الخروج المؤقت"
                    ),
                ),
                (
                    "elimination_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الحذف أو الإقصاء"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
            ],
            options={
                "verbose_name": "وثيقة أرشيف",
                "verbose_name_plural": "وثائق الأرشيف",
            },
        ),
    ]
