# Generated by Django 6.0.2 on 2026-02-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_employeeprofile_assigned_interface_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeprofile",
            name="assigned_interface",
        ),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="is_active_cloud",
        ),
    ]
