# Generated by Django 6.0.2 on 2026-02-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_archivedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="permissions",
            field=models.JSONField(blank=True, default=list, verbose_name="الصلاحيات"),
        ),
    ]
