# Generated by Django 6.0.2 on 2026-02-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_employeeprofile_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="admin_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="البريد الإلكتروني لاستعادة كلمة المرور",
            ),
        ),
    ]
