# Generated by Django 6.0.2 on 2026-02-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_remove_employeeprofile_assigned_interface_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolsettings",
            name="academic_year",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="السنة الدراسية"
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="director_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="اسم المدير"
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="اسم المؤسسة"
            ),
        ),
    ]
