# Generated by Django 6.0.2 on 2026-02-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0011_schoolsettings_admin_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryloan",
            name="loan_time",
            field=models.TimeField(
                auto_now_add=True, null=True, verbose_name="وقت الإعارة"
            ),
        ),
    ]
