# Generated by Django 6.0.2 on 2026-02-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0011_alter_schoolsettings_academic_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolsettings",
            name="canteen_close_time",
            field=models.TimeField(
                blank=True, default="13:15", null=True, verbose_name="وقت غلق المطعم"
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="canteen_days",
            field=models.CharField(
                blank=True,
                default="0,2,3,6",
                max_length=50,
                null=True,
                verbose_name="أيام عمل المطعم",
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="canteen_open_time",
            field=models.TimeField(
                blank=True, default="12:00", null=True, verbose_name="وقت فتح المطعم"
            ),
        ),
    ]
