# Generated by Django 6.0.2 on 2026-02-21 18:54

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0012_alter_schoolsettings_canteen_close_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="photo_path",
        ),
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=students.models.student_photo_path,
                verbose_name="الصورة",
            ),
        ),
    ]
