# Generated by Django 6.0.2 on 2026-02-08 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0012_libraryloan_loan_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                ("active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة النظام",
                "verbose_name_plural": "رسائل النظام",
            },
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="device_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="معرف الجهاز"
            ),
        ),
        migrations.CreateModel(
            name="PendingUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=50, verbose_name="النموذج")),
                ("action", models.CharField(max_length=20, verbose_name="الإجراء")),
                ("data", models.JSONField(verbose_name="البيانات")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="التوقيت"),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=20, verbose_name="الحالة"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تحديث معلق",
                "verbose_name_plural": "التحديثات المعلقة",
                "ordering": ["-timestamp"],
            },
        ),
    ]
