# Generated by Django 6.0.2 on 2026-02-23 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0013_remove_student_photo_path_student_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("content", models.TextField(verbose_name="المحتوى")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("rule", "قانون داخلي"),
                            ("curriculum", "منهاج دراسي"),
                            ("solution", "حل سابق"),
                            ("general", "عام"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ذاكرة المؤسسة",
                "verbose_name_plural": "ذاكرة المؤسسة",
            },
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="ai_focus",
            field=models.CharField(
                default="academic", max_length=50, verbose_name="تركيز الذكاء الاصطناعي"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="ai_tone",
            field=models.CharField(
                default="professional",
                max_length=50,
                verbose_name="نبرة الذكاء الاصطناعي",
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان المهمة"),
                ),
                ("description", models.TextField(verbose_name="الوصف التقني")),
                (
                    "manager_instructions",
                    models.TextField(
                        blank=True, null=True, verbose_name="سياق المدير (AI Context)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاستحقاق"
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "assigned_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.userrole",
                        verbose_name="الدور المسند",
                    ),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسند",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة",
                "verbose_name_plural": "المهام",
            },
        ),
        migrations.CreateModel(
            name="TeacherObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="ملاحظة الأستاذ")),
                (
                    "ai_suggestion",
                    models.TextField(
                        blank=True, null=True, verbose_name="مقترح الذكاء الاصطناعي"
                    ),
                ),
                (
                    "final_content",
                    models.TextField(
                        blank=True, null=True, verbose_name="المحتوى النهائي"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("ai_suggested", "مقترح AI"),
                            ("teacher_approved", "موافقة الأستاذ"),
                            ("admin_review", "مراجعة المدير"),
                            ("delivered", "تم التسليم"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_feedback",
                    models.TextField(blank=True, null=True, verbose_name="رد الإدارة"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                        verbose_name="التلميذ",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الأستاذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملاحظة تربوية",
                "verbose_name_plural": "الملاحظات التربوية",
            },
        ),
    ]
