# Generated by Django 6.0.2 on 2026-02-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0013_systemmessage_employeeprofile_device_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="عنوان السكن"),
        ),
        migrations.AlterField(
            model_name="student",
            name="guardian_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="اسم الولي"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="guardian_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="رقم هاتف الولي"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="mother_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="لقب واسم الأم"
            ),
        ),
    ]
