# Generated by Django 6.0.2 on 2026-02-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0014_schoolmemory_schoolsettings_ai_focus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolmemory",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="rag_docs/", verbose_name="ملف مرفق"
            ),
        ),
        migrations.AddField(
            model_name="schoolmemory",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="رابط مرجعي"),
        ),
    ]
