# Generated by Django 6.0.2 on 2026-02-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0014_alter_student_address_alter_student_guardian_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="canteen_close_time",
            field=models.TimeField(default="13:15", verbose_name="وقت غلق المطعم"),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="canteen_days",
            field=models.CharField(
                default="0,2,3,6", max_length=50, verbose_name="أيام عمل المطعم"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="canteen_open_time",
            field=models.TimeField(default="12:00", verbose_name="وقت فتح المطعم"),
        ),
    ]
