# Generated by Django 6.0.2 on 2026-02-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0015_schoolsettings_canteen_close_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="totp_enabled",
            field=models.BooleanField(
                default=False, verbose_name="تفعيل المصادقة الثنائية"
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="totp_secret",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="مفتاح المصادقة الثنائية",
            ),
        ),
    ]
