# Generated by Django 6.0.2 on 2026-02-23 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0015_schoolmemory_attachment_schoolmemory_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="effective_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ السريان"),
        ),
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="البريد الإلكتروني"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="الرمز الوظيفي",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="first_name",
            field=models.CharField(default="", max_length=100, verbose_name="الاسم"),
        ),
        migrations.AddField(
            model_name="employee",
            name="grade",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="الدرجة"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(default="", max_length=100, verbose_name="اللقب"),
        ),
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="employee_photos/",
                verbose_name="الصورة",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="rank",
            field=models.CharField(
                choices=[
                    ("teacher", "أستاذ"),
                    ("worker", "عامل مهني"),
                    ("admin", "إداري"),
                ],
                default="worker",
                max_length=20,
                verbose_name="الرتبة",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="subject",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="المادة"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_hr",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حساب المستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ الازدياد"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="full_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="الاسم الكامل (قديم)",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="الوظيفة (قديم)"
            ),
        ),
        migrations.CreateModel(
            name="TeacherAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100, verbose_name="المادة")),
                (
                    "classes",
                    models.JSONField(default=list, verbose_name="الأقسام المسندة"),
                ),
                (
                    "original_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assignments/",
                        verbose_name="ملف الإسناد",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="students.employee",
                        verbose_name="الأستاذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "إسناد تربوي",
                "verbose_name_plural": "الإسنادات التربوية",
            },
        ),
    ]
