# Generated by Django 6.0.2 on 2026-02-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0016_employeeprofile_totp_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم الدور"
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(default=list, verbose_name="الصلاحيات"),
                ),
            ],
            options={
                "verbose_name": "دور مخصص",
                "verbose_name_plural": "أدوار مخصصة",
            },
        ),
    ]
