# Generated by Django 6.0.2 on 2026-02-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0016_employee_effective_date_employee_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="social_media_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="رابط التواصل الاجتماعي"
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="ai_mode",
            field=models.CharField(
                choices=[
                    ("restricted_rag", "وضع مقيد (RAG) - مساعد إداري"),
                    ("educational_free", "وضع حر (تربوي)"),
                    ("full_comprehensive", "وضع شامل (Gemini Pro Full)"),
                ],
                default="restricted_rag",
                max_length=30,
                verbose_name="صلاحيات الذكاء الاصطناعي",
            ),
        ),
    ]
