# Generated by Django 6.0.2 on 2026-02-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0017_employee_social_media_link_employeeprofile_ai_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="الاسم المستعار (من الملف)",
                    ),
                ),
                (
                    "canonical_class",
                    models.CharField(
                        max_length=50, verbose_name="الاسم الرسمي (في القاعدة)"
                    ),
                ),
            ],
            options={
                "verbose_name": "تعيين اسم القسم",
                "verbose_name_plural": "تعيينات أسماء الأقسام",
            },
        ),
    ]
