# Generated by Django 6.0.2 on 2026-02-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0018_classalias"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "verbose_name": "ملاحظة تربوية",
                "verbose_name_plural": "الملاحظات التربوية",
            },
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="ai_mode",
            field=models.CharField(
                choices=[
                    ("restricted_rag", "وضع مقيد (RAG) - مساعد إداري"),
                    ("full_comprehensive", "وضع شامل (Gemini Pro Full)"),
                ],
                default="restricted_rag",
                max_length=30,
                verbose_name="صلاحيات الذكاء الاصطناعي",
            ),
        ),
        migrations.DeleteModel(
            name="TeacherObservation",
        ),
    ]
