# Generated by Django 6.0.2 on 2026-02-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0019_alter_employeeprofile_ai_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classalias",
            name="canonical_level",
            field=models.CharField(
                default="", max_length=50, verbose_name="المستوى الموافق (في القاعدة)"
            ),
        ),
        migrations.AlterField(
            model_name="classalias",
            name="canonical_class",
            field=models.CharField(
                max_length=50, verbose_name="القسم الموافق (في القاعدة)"
            ),
        ),
    ]
