# Generated by Django 6.0.2 on 2026-02-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0019_alter_employeeprofile_ai_mode_and_more"),
        ("students", "0020_classalias_canonical_level_and_more"),
    ]

    operations = []
