# Generated by Django 6.0.2 on 2026-03-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0020_classalias_canonical_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_repeater",
            field=models.BooleanField(default=False, verbose_name="معيد"),
        ),
    ]
