# Generated by Django 6.0.2 on 2026-02-28 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0020_classalias_canonical_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias_name",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="الاسم المستعار (من الملف)",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="students.employee",
                        verbose_name="الأستاذ الموافق (في القاعدة)",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعيين اسم الأستاذ",
                "verbose_name_plural": "تعيينات أسماء الأساتذة",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100, verbose_name="المادة")),
                ("term", models.CharField(max_length=50, verbose_name="الفصل")),
                ("score", models.FloatField(verbose_name="العلامة")),
                (
                    "academic_year",
                    models.CharField(
                        default="2023-2024",
                        max_length=20,
                        verbose_name="السنة الدراسية",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="students.student",
                        verbose_name="التلميذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "علامة التلميذ",
                "verbose_name_plural": "علامات التلاميذ",
                "unique_together": {("student", "subject", "term", "academic_year")},
            },
        ),
    ]
