# Generated by Django 6.0.2 on 2026-03-10 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0023_populate_class_shortcuts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertAnalysisRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=20, verbose_name="السنة الدراسية"),
                ),
                ("term", models.CharField(max_length=50, verbose_name="الفصل")),
                (
                    "run_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ المعالجة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="completed", max_length=50, verbose_name="الحالة"
                    ),
                ),
            ],
            options={
                "verbose_name": "تشغيلة تحليل الخبراء",
                "verbose_name_plural": "تشغيلات تحليل الخبراء",
                "ordering": ["-run_date"],
            },
        ),
        migrations.CreateModel(
            name="CohortExpertData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year_level",
                    models.CharField(max_length=20, verbose_name="المستوى"),
                ),
                (
                    "correlation_matrix",
                    models.JSONField(default=dict, verbose_name="مصفوفة الارتباط"),
                ),
                (
                    "current_year_z_score_avg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="متوسط Z-Score الحالي"
                    ),
                ),
                (
                    "last_year_z_score_avg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="متوسط Z-Score السابق"
                    ),
                ),
                (
                    "cohort_effect_analysis",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="تحليل أثر الفوج",
                    ),
                ),
                (
                    "sensitivity_betas",
                    models.JSONField(
                        default=dict, verbose_name="معاملات الحساسية (Beta)"
                    ),
                ),
                (
                    "ruling_subject",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="المادة الحاكمة",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohort_data",
                        to="students.expertanalysisrun",
                        verbose_name="التشغيلة",
                    ),
                ),
            ],
            options={
                "verbose_name": "بيانات الفوج (الخبراء)",
                "verbose_name_plural": "بيانات الأفواج (الخبراء)",
            },
        ),
        migrations.CreateModel(
            name="StudentExpertData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=20, verbose_name="القسم")),
                (
                    "academic_year_level",
                    models.CharField(max_length=20, verbose_name="المستوى"),
                ),
                (
                    "residual",
                    models.FloatField(
                        blank=True, null=True, verbose_name="الباقي (Residual)"
                    ),
                ),
                (
                    "status_pattern",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="نمط التلميذ"
                    ),
                ),
                (
                    "current_avg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="المعدل الحالي"
                    ),
                ),
                (
                    "predicted_avg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="المعدل المتوقع"
                    ),
                ),
                (
                    "traffic_light",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="إشارة المرور",
                    ),
                ),
                (
                    "trend_history",
                    models.JSONField(default=list, verbose_name="سجل الاتجاه"),
                ),
                (
                    "net_value_added",
                    models.FloatField(
                        blank=True, null=True, verbose_name="القيمة المضافة الصافية"
                    ),
                ),
                (
                    "z_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="الدرجة المعيارية (Z-Score)"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_data",
                        to="students.expertanalysisrun",
                        verbose_name="التشغيلة",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                        verbose_name="التلميذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "بيانات التلميذ (الخبراء)",
                "verbose_name_plural": "بيانات التلاميذ (الخبراء)",
            },
        ),
    ]
