# Generated by Django 6.0.2 on 2026-03-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0024_expertanalysisrun_cohortexpertdata_studentexpertdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="class_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="رمز القسم"
            ),
        ),
    ]
