# Generated by Django 6.0.2 on 2026-03-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    # This ensures that it just applies after the latest migration available in the local environment,
    # preventing NodeNotFoundError if a specific intermediate migration (like 0024) is missing or renamed locally.
    # Note: the "__latest__" is generally valid in dependencies if properly structured, but setting to None or matching
    # the last confirmed baseline (0023) is safer here since 0024 might be entirely missing for the user.
    dependencies = [
        ("students", "0023_populate_class_shortcuts"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="class_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="رمز القسم"
            ),
        ),
    ]
