# Generated by Django 6.0.2 on 2026-03-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0024_expertanalysisrun_cohortexpertdata_studentexpertdata"),
        ("students", "0025_student_class_code"),
    ]

    operations = []
