# Generated by Django 6.0.2 on 2026-03-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0026_merge_20260313_1428"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="الاسم المستعار (من الملف)",
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(
                        max_length=100, verbose_name="المادة الموافقة (في القاعدة)"
                    ),
                ),
            ],
            options={
                "verbose_name": "تعيين اسم المادة",
                "verbose_name_plural": "تعيينات أسماء المواد",
            },
        ),
    ]
