# Generated by Django 6.0.2 on 2026-03-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0027_subjectalias"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="analytics_assignments",
            field=models.JSONField(
                blank=True, default=list, verbose_name="الإسنادات الخاصة بالتحليل"
            ),
        ),
    ]
