# Generated by Django 6.0.2 on 2026-03-14 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0028_employee_analytics_assignments"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("academic_year", models.CharField(max_length=50)),
                ("class_name", models.CharField(max_length=50)),
                ("class_code", models.CharField(blank=True, max_length=20, null=True)),
                ("historical_year", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("term", models.CharField(max_length=50)),
                ("score", models.FloatField()),
                ("historical_year", models.CharField(max_length=20)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.historicalstudent",
                    ),
                ),
            ],
        ),
    ]
