import os

migration_content = """# Generated by Django 6.0.2 on 2026-03-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0021_student_is_repeater"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassShortcut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="الاسم الكامل للقسم"
                    ),
                ),
                (
                    "shortcut",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="اختصار القسم"
                    ),
                ),
            ],
            options={
                "verbose_name": "اختصار القسم",
                "verbose_name_plural": "اختصارات الأقسام",
            },
        ),
    ]
"""

# Path to the missing migration file
file_path = os.path.join('students', 'migrations', '0022_classshortcut.py')

# Ensure directory exists
os.makedirs(os.path.dirname(file_path), exist_ok=True)

# Write the file
with open(file_path, 'w', encoding='utf-8') as f:
    f.write(migration_content)

print(f"✅ Successfully created missing migration file: {file_path}")
print("Now run: python manage.py migrate")
